[workspace]
members = ["http-acl", "http-acl-reqwest"]
resolver = "2"

[workspace.package]
version = "0.5.6"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/nethunterslabs/http-acl"
categories = ["network-programming", "web-programming::http-client"]
keywords = ["http", "acl", "ip", "network", "ssrf"]
