[workspace]
members = ["http-acl", "http-acl-reqwest"]
resolver = "2"

[workspace.package]
version = "0.6.4"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/nethunterslabs/http-acl"
categories = ["network-programming", "web-programming::http-client"]
keywords = ["http", "acl", "ip", "network", "ssrf"]

[workspace.dependencies]
anyhow = "1.0.95"
async-trait = "0.1.86"
futures-util-preview = "0.2.2"
http = "1.2.0"
ipnet = "2.11.0"
matchit = "0.8.6"
reqwest = { version = "0.12.12", default-features = false }
reqwest-middleware = "0.4.0"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
url = "2.5.4"
