[package]
name = "http-acl"
description = "An ACL for HTTP requests."
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
ipnet = "2.8.0"
url = "2.4.0"
